# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2262e42d52cb8bbf305ec6be91f112e1fe18960fedb543d5fa12e2836d29de2f59fbf0f77a7514e56ed8a525e47b508260839ec92d752c4656f5e9cc6af2bdbf

test:
  secret_key_base: 9554c00e0915781d1b0cf0f7d1ffe776bb8d0d059425f95e5e0c6accd648ada3f1b178ab129b1dfc1bb804d8442c92b64b375d52da5098f34c6ff4899959aaf7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
